#!/usr/bin/env python3
"""
End-to-end abstain smoke test.

Loads the trained checkpoint, runs a handful of in-scope and OOD images
through it (sampled from the negatives + test split), and asserts:
  - non-marine images either predict `nothing` outright OR fail the
    calibrated thresholds
  - in-scope images survive the same gate

Exits 0 on success, 1 on any failure. Prints a small table for human
inspection regardless.

Defaults pick the first checkpoint we can find under ml/models, prefer the
21-class fine-tuned run if present, and use the bundled thresholds.json if
one was generated by evaluate_ood.py.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import sys
from pathlib import Path

import torch
from PIL import Image

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from ml.training.dataset import get_val_transforms
from ml.training.model import load_trained_model

DEFAULT_THRESHOLDS = {
    "minimumDetectionConfidence": 0.55,
    "minimumTopMargin": 0.10,
    "maxEntropyRatio": 0.65,
    "nothingClassId": "nothing",
}


def _load_thresholds(path: Path | None) -> dict:
    if path is None or not path.exists():
        print(f"(using fallback thresholds: {DEFAULT_THRESHOLDS})")
        return dict(DEFAULT_THRESHOLDS)
    with path.open("r", encoding="utf-8") as f:
        loaded = json.load(f)
    out = dict(DEFAULT_THRESHOLDS)
    for k in DEFAULT_THRESHOLDS:
        if k in loaded:
            out[k] = loaded[k]
    print(f"(using calibrated thresholds from {path}: {out})")
    return out


def _sample_paths(csv_path: Path, n: int, *, want_label: str | None, exclude_label: str | None, seed: int) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    with csv_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            label = (row.get("class_label") or row.get("source_taxon") or "").strip()
            path = (row.get("image_path") or row.get("local_path") or "").strip()
            if not path or not os.path.exists(path):
                continue
            if want_label is not None and label != want_label:
                continue
            if exclude_label is not None and label == exclude_label:
                continue
            rows.append((path, label))
    rng = random.Random(seed)
    rng.shuffle(rows)
    return rows[:n]


def _decide(probs: torch.Tensor, idx_to_class: dict[int, str], thresholds: dict) -> tuple[str, dict]:
    """Mirror the iOS-side decision logic. Returns (decision, debug)."""
    nothing_id = thresholds.get("nothingClassId", "nothing")
    nothing_idx = next((i for i, n in idx_to_class.items() if n == nothing_id), None)

    top2 = torch.topk(probs, k=min(2, probs.numel())).indices.tolist()
    top_idx = top2[0]
    top_p = probs[top_idx].item()
    second_p = probs[top2[1]].item() if len(top2) > 1 else 0.0
    p_clamped = probs.clamp_min(1e-12)
    entropy = -(p_clamped * p_clamped.log()).sum().item()
    entropy_ratio = entropy / math.log(probs.numel()) if probs.numel() > 1 else 0.0

    debug = {
        "top_class": idx_to_class[top_idx],
        "top_prob": round(top_p, 4),
        "margin": round(top_p - second_p, 4),
        "entropy_ratio": round(entropy_ratio, 4),
    }

    if nothing_idx is not None and top_idx == nothing_idx:
        return "abstain:nothing_argmax", debug
    if top_p < thresholds["minimumDetectionConfidence"]:
        return "abstain:low_confidence", debug
    if (top_p - second_p) < thresholds["minimumTopMargin"]:
        return "abstain:low_margin", debug
    if entropy_ratio > thresholds["maxEntropyRatio"]:
        return "abstain:high_entropy", debug
    return f"accept:{idx_to_class[top_idx]}", debug


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Smoke test the abstain pipeline")
    parser.add_argument("--model", type=Path, required=True, help="Path to trained checkpoint")
    parser.add_argument("--in-scope-csv", type=Path, default=PROJECT_ROOT / "ml" / "data" / "splits" / "test.csv")
    parser.add_argument("--negatives-manifest", type=Path, default=PROJECT_ROOT / "ml" / "data" / "negatives_manifest.csv")
    parser.add_argument("--thresholds-json", type=Path, default=None)
    parser.add_argument("--n-per-side", type=int, default=8)
    parser.add_argument("--seed", type=int, default=7)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    thresholds = _load_thresholds(args.thresholds_json)

    if torch.backends.mps.is_available():
        device = torch.device("mps")
    elif torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")

    print(f"Loading model: {args.model}")
    model, class_to_idx = load_trained_model(
        str(args.model), device=str(device), return_class_mapping=True
    )
    model = model.to(device).eval()
    idx_to_class = {idx: name for name, idx in class_to_idx.items()}

    in_scope = _sample_paths(
        args.in_scope_csv, n=args.n_per_side,
        want_label=None, exclude_label="nothing", seed=args.seed,
    )
    if not args.negatives_manifest.exists():
        print(f"WARN: {args.negatives_manifest} missing; falling back to in-scope-only smoke")
        ood = []
    else:
        ood = _sample_paths(
            args.negatives_manifest, n=args.n_per_side,
            want_label=None, exclude_label=None, seed=args.seed + 1,
        )

    transform = get_val_transforms()
    rows: list[tuple[str, str, str, dict, bool]] = []
    failures = 0

    print("\n--- IN-SCOPE (expect accept) ---")
    for path, label in in_scope:
        img = Image.open(path).convert("RGB")
        x = transform(img).unsqueeze(0).to(device)
        with torch.no_grad():
            logits = model(x)
            probs = torch.softmax(logits, dim=1).squeeze(0).cpu()
        decision, debug = _decide(probs, idx_to_class, thresholds)
        ok = decision.startswith("accept")
        rows.append(("in_scope", label, decision, debug, ok))
        if not ok:
            failures += 1
        print(f"  [{'PASS' if ok else 'FAIL'}] expected:{label}  -> {decision}  {debug}")

    if ood:
        print("\n--- OOD (expect abstain) ---")
        for path, source in ood:
            img = Image.open(path).convert("RGB")
            x = transform(img).unsqueeze(0).to(device)
            with torch.no_grad():
                logits = model(x)
                probs = torch.softmax(logits, dim=1).squeeze(0).cpu()
            decision, debug = _decide(probs, idx_to_class, thresholds)
            ok = decision.startswith("abstain")
            rows.append(("ood", source, decision, debug, ok))
            if not ok:
                failures += 1
            print(f"  [{'PASS' if ok else 'FAIL'}] source:{source}  -> {decision}  {debug}")

    n_total = len(rows)
    n_pass = n_total - failures
    print(f"\nResult: {n_pass}/{n_total} expected behavior")
    if failures > 0:
        print("FAIL: smoke test detected unexpected decisions.")
        return 1
    print("PASS: smoke test green.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
